dataset_name: antmaze-umaze-diverse-v2
eval_episodes: 100
eval_every: 50
normalize_reward: True
actor_learning_rate: 6e-4
critic_learning_rate: 6e-4
alpha_learning_rate: 6e-4
batch_size: 1024
critic_ln: True
num_critics: 25
