project: ClORL
command:
  - ${env}
  - python3
  - ${program}
  - ${args}
method: grid
parameters:
  config_path:
    values:
      - configs/offline/iql-ce-at/hopper/medium_replay_v2.yaml
      - configs/offline/iql-ce-at/hopper/medium_v2.yaml
      - configs/offline/iql-ce-at/hopper/medium_expert_v2.yaml
      - configs/offline/iql-ce-at/halfcheetah/medium_replay_v2.yaml
      - configs/offline/iql-ce-at/halfcheetah/medium_v2.yaml
      - configs/offline/iql-ce-at/halfcheetah/medium_expert_v2.yaml
      - configs/offline/iql-ce-at/walker2d/medium_replay_v2.yaml
      - configs/offline/iql-ce-at/walker2d/medium_v2.yaml
      - configs/offline/iql-ce-at/walker2d/medium_expert_v2.yaml
      - configs/offline/iql-ce-at/pen/human_v1.yaml
      - configs/offline/iql-ce-at/pen/cloned_v1.yaml
      - configs/offline/iql-ce-at/pen/expert_v1.yaml
      - configs/offline/iql-ce-at/door/human_v1.yaml
      - configs/offline/iql-ce-at/door/cloned_v1.yaml
      - configs/offline/iql-ce-at/door/expert_v1.yaml
      - configs/offline/iql-ce-at/hammer/human_v1.yaml
      - configs/offline/iql-ce-at/hammer/cloned_v1.yaml
      - configs/offline/iql-ce-at/hammer/expert_v1.yaml
      - configs/offline/iql-ce-at/relocate/human_v1.yaml
      - configs/offline/iql-ce-at/relocate/cloned_v1.yaml
      - configs/offline/iql-ce-at/relocate/expert_v1.yaml
      - configs/offline/iql-ce-at/hopper/full_replay_v2.yaml
      - configs/offline/iql-ce-at/hopper/random_v2.yaml
      - configs/offline/iql-ce-at/hopper/expert_v2.yaml
      - configs/offline/iql-ce-at/halfcheetah/full_replay_v2.yaml
      - configs/offline/iql-ce-at/halfcheetah/random_v2.yaml
      - configs/offline/iql-ce-at/halfcheetah/expert_v2.yaml
      - configs/offline/iql-ce-at/walker2d/full_replay_v2.yaml
      - configs/offline/iql-ce-at/walker2d/random_v2.yaml
      - configs/offline/iql-ce-at/walker2d/expert_v2.yaml
      - configs/offline/iql-ce-at/antmaze/umaze_v2.yaml
      - configs/offline/iql-ce-at/antmaze/umaze_diverse_v2.yaml
      - configs/offline/iql-ce-at/antmaze/medium_play_v2.yaml
      - configs/offline/iql-ce-at/antmaze/medium_diverse_v2.yaml
      - configs/offline/iql-ce-at/antmaze/large_play_v2.yaml
      - configs/offline/iql-ce-at/antmaze/large_diverse_v2.yaml
  train_seed:
    values:
      - 10
      - 11
      - 12
      - 13
program: src/algorithms/iql_cl.py

