command:
  - ${env}
  - python3
  - ${program}
  - ${args}
method: grid
metric:
  goal: maximize
  name: eval/normalized_score_mean
name: IQL Eval CE+MT
parameters:
  batch_size:
    value: 256
  config_path:
    values:
      - configs/offline/iql-ce-mt/halfcheetah/medium_replay_v2.yaml
      - configs/offline/iql-ce-mt/halfcheetah/medium_v2.yaml
      - configs/offline/iql-ce-mt/halfcheetah/medium_expert_v2.yaml
      - configs/offline/iql-ce-mt/halfcheetah/random_v2.yaml
      - configs/offline/iql-ce-mt/halfcheetah/expert_v2.yaml
      - configs/offline/iql-ce-mt/halfcheetah/full_replay_v2.yaml
      - configs/offline/iql-ce-mt/hammer/expert_v1.yaml
      - configs/offline/iql-ce-mt/hammer/human_v1.yaml
      - configs/offline/iql-ce-mt/hammer/cloned_v1.yaml
      - configs/offline/iql-ce-mt/hopper/medium_replay_v2.yaml
      - configs/offline/iql-ce-mt/hopper/medium_v2.yaml
      - configs/offline/iql-ce-mt/hopper/medium_expert_v2.yaml
      - configs/offline/iql-ce-mt/hopper/random_v2.yaml
      - configs/offline/iql-ce-mt/hopper/expert_v2.yaml
      - configs/offline/iql-ce-mt/hopper/full_replay_v2.yaml
      - configs/offline/iql-ce-mt/door/expert_v1.yaml
      - configs/offline/iql-ce-mt/door/human_v1.yaml
      - configs/offline/iql-ce-mt/door/cloned_v1.yaml
      - configs/offline/iql-ce-mt/antmaze/umaze_v2.yaml
      - configs/offline/iql-ce-mt/antmaze/medium_play_v2.yaml
      - configs/offline/iql-ce-mt/antmaze/medium_diverse_v2.yaml
      - configs/offline/iql-ce-mt/antmaze/large_diverse_v2.yaml
      - configs/offline/iql-ce-mt/antmaze/umaze_diverse_v2.yaml
      - configs/offline/iql-ce-mt/antmaze/large_play_v2.yaml
      - configs/offline/iql-ce-mt/relocate/expert_v1.yaml
      - configs/offline/iql-ce-mt/relocate/human_v1.yaml
      - configs/offline/iql-ce-mt/relocate/cloned_v1.yaml
      - configs/offline/iql-ce-mt/walker2d/medium_replay_v2.yaml
      - configs/offline/iql-ce-mt/walker2d/medium_v2.yaml
      - configs/offline/iql-ce-mt/walker2d/medium_expert_v2.yaml
      - configs/offline/iql-ce-mt/walker2d/random_v2.yaml
      - configs/offline/iql-ce-mt/walker2d/expert_v2.yaml
      - configs/offline/iql-ce-mt/walker2d/full_replay_v2.yaml
      - configs/offline/iql-ce-mt/pen/expert_v1.yaml
      - configs/offline/iql-ce-mt/pen/human_v1.yaml
      - configs/offline/iql-ce-mt/pen/cloned_v1.yaml
  sigma_frac:
    value: 0.75
  temperature:
    value: 3
  train_seed:
    values:
      - 10
      - 11
      - 12
      - 13
  v_expand_mode:
    value: both
program: src/algorithms/iql_cl.py