command:
  - ${env}
  - python3
  - ${program}
  - ${args}
method: grid
name: ReBRAC Eval CE+MT
parameters:
  config_path:
    values:
      - configs/offline/rebrac-ce-mt/hopper/full_replay_v2.yaml
      - configs/offline/rebrac-ce-mt/hopper/random_v2.yaml
      - configs/offline/rebrac-ce-mt/hopper/expert_v2.yaml
      - configs/offline/rebrac-ce-mt/halfcheetah/full_replay_v2.yaml
      - configs/offline/rebrac-ce-mt/halfcheetah/random_v2.yaml
      - configs/offline/rebrac-ce-mt/halfcheetah/expert_v2.yaml
      - configs/offline/rebrac-ce-mt/walker2d/full_replay_v2.yaml
      - configs/offline/rebrac-ce-mt/walker2d/random_v2.yaml
      - configs/offline/rebrac-ce-mt/walker2d/expert_v2.yaml
      - configs/offline/rebrac-ce-mt/hopper/medium_replay_v2.yaml
      - configs/offline/rebrac-ce-mt/hopper/medium_v2.yaml
      - configs/offline/rebrac-ce-mt/hopper/medium_expert_v2.yaml
      - configs/offline/rebrac-ce-mt/halfcheetah/medium_replay_v2.yaml
      - configs/offline/rebrac-ce-mt/halfcheetah/medium_v2.yaml
      - configs/offline/rebrac-ce-mt/halfcheetah/medium_expert_v2.yaml
      - configs/offline/rebrac-ce-mt/walker2d/medium_replay_v2.yaml
      - configs/offline/rebrac-ce-mt/walker2d/medium_v2.yaml
      - configs/offline/rebrac-ce-mt/walker2d/medium_expert_v2.yaml
      - configs/offline/rebrac-ce-mt/antmaze/umaze_v2.yaml
      - configs/offline/rebrac-ce-mt/antmaze/umaze_diverse_v2.yaml
      - configs/offline/rebrac-ce-mt/antmaze/medium_play_v2.yaml
      - configs/offline/rebrac-ce-mt/antmaze/medium_diverse_v2.yaml
      - configs/offline/rebrac-ce-mt/antmaze/large_play_v2.yaml
      - configs/offline/rebrac-ce-mt/antmaze/large_diverse_v2.yaml
      - configs/offline/rebrac-ce-mt/pen/human_v1.yaml
      - configs/offline/rebrac-ce-mt/pen/cloned_v1.yaml
      - configs/offline/rebrac-ce-mt/pen/expert_v1.yaml
      - configs/offline/rebrac-ce-mt/door/human_v1.yaml
      - configs/offline/rebrac-ce-mt/door/cloned_v1.yaml
      - configs/offline/rebrac-ce-mt/door/expert_v1.yaml
      - configs/offline/rebrac-ce-mt/hammer/human_v1.yaml
      - configs/offline/rebrac-ce-mt/hammer/cloned_v1.yaml
      - configs/offline/rebrac-ce-mt/hammer/expert_v1.yaml
      - configs/offline/rebrac-ce-mt/relocate/human_v1.yaml
      - configs/offline/rebrac-ce-mt/relocate/cloned_v1.yaml
      - configs/offline/rebrac-ce-mt/relocate/expert_v1.yaml
  num_epochs:
    value: 1000
  sigma_frac:
    value: 0.75
  train_seed:
    values:
      - 10
      - 11
      - 12
      - 13
program: src/algorithms/rebrac_cl.py