command:
  - ${env}
  - python3
  - ${program}
  - ${args}
method: grid
metric:
  goal: maximize
  name: eval/normalized_score_mean
name: Tuned parameters iql. Dataset sweep
parameters:
  batch_size:
    value: 256
  config_path:
    values:
      - configs/offline/iql-ce/halfcheetah/medium_replay_v2.yaml
      - configs/offline/iql-ce/halfcheetah/medium_v2.yaml
      - configs/offline/iql-ce/halfcheetah/medium_expert_v2.yaml
      - configs/offline/iql-ce/halfcheetah/random_v2.yaml
      - configs/offline/iql-ce/halfcheetah/expert_v2.yaml
      - configs/offline/iql-ce/halfcheetah/full_replay_v2.yaml
      - configs/offline/iql-ce/hammer/expert_v1.yaml
      - configs/offline/iql-ce/hammer/human_v1.yaml
      - configs/offline/iql-ce/hammer/cloned_v1.yaml
      - configs/offline/iql-ce/hopper/medium_replay_v2.yaml
      - configs/offline/iql-ce/hopper/medium_v2.yaml
      - configs/offline/iql-ce/hopper/medium_expert_v2.yaml
      - configs/offline/iql-ce/hopper/random_v2.yaml
      - configs/offline/iql-ce/hopper/expert_v2.yaml
      - configs/offline/iql-ce/hopper/full_replay_v2.yaml
      - configs/offline/iql-ce/door/expert_v1.yaml
      - configs/offline/iql-ce/door/human_v1.yaml
      - configs/offline/iql-ce/door/cloned_v1.yaml
      - configs/offline/iql-ce/antmaze/umaze_v2.yaml
      - configs/offline/iql-ce/antmaze/medium_play_v2.yaml
      - configs/offline/iql-ce/antmaze/medium_diverse_v2.yaml
      - configs/offline/iql-ce/antmaze/large_diverse_v2.yaml
      - configs/offline/iql-ce/antmaze/umaze_diverse_v2.yaml
      - configs/offline/iql-ce/antmaze/large_play_v2.yaml
      - configs/offline/iql-ce/relocate/expert_v1.yaml
      - configs/offline/iql-ce/relocate/human_v1.yaml
      - configs/offline/iql-ce/relocate/cloned_v1.yaml
      - configs/offline/iql-ce/walker2d/medium_replay_v2.yaml
      - configs/offline/iql-ce/walker2d/medium_v2.yaml
      - configs/offline/iql-ce/walker2d/medium_expert_v2.yaml
      - configs/offline/iql-ce/walker2d/random_v2.yaml
      - configs/offline/iql-ce/walker2d/expert_v2.yaml
      - configs/offline/iql-ce/walker2d/full_replay_v2.yaml
      - configs/offline/iql-ce/pen/expert_v1.yaml
      - configs/offline/iql-ce/pen/human_v1.yaml
      - configs/offline/iql-ce/pen/cloned_v1.yaml
  critic_hidden_dims:
    values:
      - - 256
        - 256
      - - 256
        - 256
        - 256
      - - 256
        - 256
        - 256
        - 256
      - - 256
        - 256
        - 256
        - 256
        - 256
      - - 256
        - 256
        - 256
        - 256
        - 256
        - 256
  n_classes:
    value: 101
  sigma_frac:
    value: 0.75
  train_seed:
    values:
      - 0
      - 1
      - 2
      - 3
program: src/algorithms/iql_cl.py
