dataset_name: hopper-medium-replay-v2
eval_episodes: 10
eval_every: 10
actor_learning_rate: 17e-4
critic_learning_rate: 17e-4
alpha_learning_rate: 17e-4
batch_size: 8192
critic_ln: True
num_critics: 10
n_classes: 101
sigma_frac: 0.75
