dataset_name: door-human-v1
eval_episodes: 10
eval_every: 10
actor_learning_rate: 6e-4
critic_learning_rate: 6e-4
alpha_learning_rate: 6e-4
batch_size: 1024
critic_ln: True
num_critics: 2
n_classes: 101
sigma_frac: 0.75
v_expand: 0.
v_expand_mode: "both"
