dataset_name: walker2d-medium-replay-v2
eval_episodes: 10
eval_every: 10
actor_learning_rate: 6e-4
critic_learning_rate: 6e-4
alpha_learning_rate: 6e-4
batch_size: 1024
critic_ln: True
num_critics: 5
n_classes: 101
sigma_frac: 0.85
